version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: arx-calculator-backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    container_name: arx-calculator-frontend
    depends_on:
      - backend 